-- 수업·상담 신청 (inquiries) — 2026-06-12
-- 비로그인 사용자도 신청 가능, 조회·수정은 admin만 (RLS)

create table if not exists public.inquiries (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null,
    phone text not null,
    interest text,           -- 관심 클래스
    preferred_time text,     -- 희망 요일·시간대
    message text,            -- 문의 내용
    source text,             -- 유입경로 (인스타/블로그/검색/지인/기타) → 마케팅 KPI 실측
    status text not null default 'new',  -- new / contacted / registered / closed
    admin_note text
);

alter table public.inquiries enable row level security;

-- 누구나(비로그인 포함) 신청서 제출 가능
drop policy if exists "Anyone can submit inquiry" on public.inquiries;
create policy "Anyone can submit inquiry" on public.inquiries
    for insert to anon, authenticated with check (true);

-- 조회·수정·삭제는 admin만
drop policy if exists "Only admin can view inquiries" on public.inquiries;
create policy "Only admin can view inquiries" on public.inquiries
    for select using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

drop policy if exists "Only admin can update inquiries" on public.inquiries;
create policy "Only admin can update inquiries" on public.inquiries
    for update using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

drop policy if exists "Only admin can delete inquiries" on public.inquiries;
create policy "Only admin can delete inquiries" on public.inquiries
    for delete using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );
