-- ==========================================
-- FINAL COMPLETE SCHEMA (Geulssiin Art Center)
-- Updates: Schedule Capacity, Site Config Policies
-- ==========================================

-- ==========================================
-- 1. PROFILES & AUTH
-- ==========================================
create table if not exists public.profiles (
  id uuid not null references auth.users on delete cascade,
  email text,
  is_admin boolean default false,
  role text default 'user',   
  join_motivation text,
  referral_source text,
  name text,
  birthdate text,
  created_at timestamptz default now(),
  primary key (id)
);

-- Ensure columns exist (Idempotent)
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'role') then
        alter table public.profiles add column role text default 'user';
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'name') then
        alter table public.profiles add column name text;
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'birthdate') then
        alter table public.profiles add column birthdate text;
    end if;
end $$;

alter table public.profiles enable row level security;
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );
drop policy if exists "Admins can update any profile" on profiles;
create policy "Admins can update any profile" on profiles for update using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role, join_motivation, referral_source, is_admin, name, birthdate)
  values (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'role', 'user'),
    new.raw_user_meta_data->>'join_motivation',
    new.raw_user_meta_data->>'referral_source',
    false,
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'birthdate'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();


-- ==========================================
-- 2. SITE CONFIG (Fixed Policies)
-- ==========================================
create table if not exists public.site_config (
  key text primary key,
  value text,
  description text
);
alter table public.site_config enable row level security;

-- [FIX] Ensure Admis have INSERT permission for Upsert to work
drop policy if exists "Config viewable by everyone" on site_config;
create policy "Config viewable by everyone" on site_config for select using ( true );

drop policy if exists "Only admin can update config" on site_config;
create policy "Only admin can update config" on site_config for update using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

drop policy if exists "Only admin can insert config" on site_config;
create policy "Only admin can insert config" on site_config for insert with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

insert into public.site_config (key, value, description)
values
  ('hero_title', '예술이 되는 글씨, 감성이 되는 그림', '메인 화면 큰 문구'),
  ('hero_subtitle', '글씨인아트센터', '메인 화면 작은 문구'),
  ('about_title', '여백 속에 담긴 묵직한 울림', '소개 페이지 제목'),
  ('about_content', '글씨인아트센터는 전통 서예의 깊이와 현대적 감각을 잇는 예술 공간입니다.\n\n붓끝에서 피어나는 기록...\n(관리자 페이지에서 수정하세요)', '소개 페이지 본문')
on conflict (key) do nothing;


-- ==========================================
-- 3. GALLERY & STORAGE
-- ==========================================
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text not null,
  category text default 'director',
  created_at timestamptz default now()
);
alter table public.gallery enable row level security;
drop policy if exists "Gallery is viewable by everyone" on gallery;
create policy "Gallery is viewable by everyone" on gallery for select using ( true );
drop policy if exists "Only admin can insert gallery" on gallery;
create policy "Only admin can insert gallery" on gallery for insert with check ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );
drop policy if exists "Only admin can update gallery" on gallery;
create policy "Only admin can update gallery" on gallery for update using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );
drop policy if exists "Only admin can delete gallery" on gallery;
create policy "Only admin can delete gallery" on gallery for delete using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );

insert into storage.buckets (id, name, public) values ('gallery_images', 'gallery_images', true) on conflict (id) do nothing;
drop policy if exists "Gallery images are publicly accessible" on storage.objects;
create policy "Gallery images are publicly accessible" on storage.objects for select using ( bucket_id = 'gallery_images' );
drop policy if exists "Admins can upload gallery images" on storage.objects;
create policy "Admins can upload gallery images" on storage.objects for insert with check ( bucket_id = 'gallery_images' and exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );
drop policy if exists "Admins can delete gallery images" on storage.objects;
create policy "Admins can delete gallery images" on storage.objects for delete using ( bucket_id = 'gallery_images' and exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );


-- ==========================================
-- 4. CLASSES (Updated Schedule Structure)
-- ==========================================
create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  day text not null,         -- '월', '화', '수'...
  start_time text not null,  -- '10:00'
  end_time text not null,    -- '12:00'
  class_name text not null,  -- '서예 기초반'
  description text,          -- '붓잡는 법부터 시작'
  max_capacity int default 0, -- [NEW]
  current_enrollment int default 0, -- [NEW]
  created_at timestamptz default now()
);

-- Add missing columns if table exists from V8 (Idempotent)
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'classes' and column_name = 'start_time') then
        alter table public.classes add column start_time text default '00:00';
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'classes' and column_name = 'end_time') then
        alter table public.classes add column end_time text default '00:00';
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'classes' and column_name = 'max_capacity') then
        alter table public.classes add column max_capacity int default 0;
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'classes' and column_name = 'current_enrollment') then
        alter table public.classes add column current_enrollment int default 0;
    end if;
end $$;

alter table public.classes enable row level security;
drop policy if exists "Classes viewable by everyone" on classes;
create policy "Classes viewable by everyone" on classes for select using ( true );
drop policy if exists "Only admin can manage classes" on classes;
create policy "Only admin can manage classes" on classes for all
  using ( exists ( select 1 from profiles where id = auth.uid() and is_admin = true ) );


-- ==========================================
-- 5. BOARD (POSTS) with Notices
-- ==========================================
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id uuid references profiles(id) on delete cascade not null,
  access_level text default 'general',
  is_notice boolean default false,
  created_at timestamptz default now()
);

do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'posts' and column_name = 'access_level') then
        alter table public.posts add column access_level text default 'general';
    end if;
    if not exists (select 1 from information_schema.columns where table_name = 'posts' and column_name = 'is_notice') then
        alter table public.posts add column is_notice boolean default false;
    end if;
end $$;

alter table public.posts enable row level security;
drop policy if exists "View posts based on access level" on posts;
create policy "View posts based on access level" on posts for select
using (
  (access_level = 'general' AND auth.role() = 'authenticated') OR
  (access_level = 'student' AND exists ( select 1 from profiles where id = auth.uid() and (role = 'student' or is_admin = true) )) OR
  (exists (select 1 from profiles where id = auth.uid() and is_admin = true))
);
drop policy if exists "Admins can insert posts" on posts;
create policy "Admins can insert posts" on posts for insert with check ( exists (select 1 from profiles where id = auth.uid() and is_admin = true) );
drop policy if exists "Admins can update posts" on posts;
create policy "Admins can update posts" on posts for update using ( exists (select 1 from profiles where id = auth.uid() and is_admin = true) );
drop policy if exists "Admins can delete posts" on posts;
create policy "Admins can delete posts" on posts for delete using ( exists (select 1 from profiles where id = auth.uid() and is_admin = true) );


-- ==========================================
-- 6. COMMENTS
-- ==========================================
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  content text not null,
  post_id bigint references posts(id) on delete cascade not null,
  author_id uuid references profiles(id) on delete cascade not null,
  created_at timestamptz default now()
);
alter table public.comments enable row level security;
drop policy if exists "Comments are viewable by members" on comments;
create policy "Comments are viewable by members" on comments for select using ( auth.role() = 'authenticated' );
drop policy if exists "Members can create comments" on comments;
create policy "Members can create comments" on comments for insert with check ( auth.uid() = author_id );
drop policy if exists "Users can delete own comments" on comments;
create policy "Users can delete own comments" on comments for delete using ( auth.uid() = author_id );

-- Safety Constraints
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'posts_author_id_fkey') THEN
        ALTER TABLE public.posts DROP CONSTRAINT posts_author_id_fkey;
    END IF;
    ALTER TABLE public.posts ADD CONSTRAINT posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
END $$;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'comments_author_id_fkey') THEN
        ALTER TABLE public.comments DROP CONSTRAINT comments_author_id_fkey;
    END IF;
    ALTER TABLE public.comments ADD CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
END $$;
